config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'hot_springs#index'
  resources :hot_springs do
    resources :comments,only: [:index, :new, :create] 
    collection do
      get 'search'
    end
  end
   resources :users, only: [:show,:edit,:update,:destroy]

   post 'like/:id' => 'likes#create', as: 'create_like'
   delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

   post 'comments_like/:id' => 'comments_likes#create', as: 'create_comments_like'
   delete 'comments_like/:id' => 'comments_likes#destroy', as: 'destroy_comments_like'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :hot_spring
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :hot_spring_params
  
  def create
    Like.create(user_id: current_user.id, hot_spring_id: params[:id])

  end

  def destroy
    Like.find_by(user_id: current_user.id, hot_spring_id: params[:id]).destroy
    
  end

  private
  
  def hot_spring_params
    @hot_spring = HotSpring.find(params[:id])
  end
  
  
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if user_signed_in? %>
  <% if current_user.liked_by?(hot_spring.id) %>
    <td>
      <%= link_to destroy_like_path(hot_spring), method: :DELETE, remote: true ,class: 'like-btn' do %>
           <i class="fa fa-heart unlike-btn"></i>
      <% end %>
      <%= hot_spring.likes.count %></td>
  <% else %>
    <td>
      <%= link_to create_like_path(hot_spring), method: :POST, remote: true,class: 'like-btn' do %>
          <i class="fa fa-heart like-btn"></i>
      <% end %>
      <%= hot_spring.likes.count %></td>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$('#hot_spring_<%= @hot_spring.id %>').html("<%= j(render partial: 'likes/like', locals: {hot_spring: @hot_spring}) %>");

app/views/likes/destroy.js.erb
$('#hot_spring_<%= @hot_spring.id %>').html("<%= j(render partial: 'likes/like', locals: {hot_spring: @hot_spring}) %>");