config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'hot_springs#index'
  resources :hot_springs do
    resources :comments,only: [:index, :new, :create] 
    collection do
      get 'search'
    end
  end
   resources :users, only: [:show,:edit,:update,:destroy]

   post 'like/:id' => 'likes#create', as: 'create_like'
   delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

   post 'comments_like/:id' => 'comments_likes#create', as: 'create_comments_like'
   delete 'comments_like/:id' => 'comments_likes#destroy', as: 'destroy_comments_like'
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 has_one_attached :image, dependent: :destroy
 has_many :comments, dependent: :destroy
 has_many :likes
 has_many :comments_likes
 has_many :hot_springs
with_options presence: true do
  validates :nickname
  validates :sex_id
end
  validates :sex_id, numericality: { other_than: 1, message: "を選択してください" }, allow_blank: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :sex

  def liked_by?(hot_spring_id)
    likes.where(hot_spring_id: hot_spring_id).exists?
  end

  def comments_liked_by?(comment_id)
    comments_likes.where(comment_id: comment_id).exists?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_q
  before_action :set_user, only: [:show,:edit,:update,:destroy]

  def show
    @comments = @user.comments
  end

  def edit
    redirect_to root_path unless (current_user.id == @user.id)
  end

  def update
    if @user.update(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  def destroy
    if current_user.id == @user.id
      @user.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end
  private

  def set_q
    @q = HotSpring.ransack(params[:q])
  end

  def set_user
    @user = User.find(params[:id])
  end
 
  def user_params
    params.require(:user).permit([:nickname,:profile,:sex_id,:image])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render "shared/header" %>
<div class="items-sell-contents">
  <div class="items-sell-main">
    <h2 class="items-sell-title">プロフィール情報を入力</h2>
    <%= form_with model:@user,url: user_path(@user.id), method: :patch,local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>
    
    <%# プロフィール画像 %>
    <div class="img-upload">
      
      <div class="weight-bold-text">
        プロフィール画像
        <span class="indispensable">任意</span>
      </div>

      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>

    </div>
    <%# /プロフィール画像 %>
  
    <%# プロフィール詳細 %>
    <div class="items-detail">
      <div class="form">
        <div class='form-text-wrap'>
           <label class="form-text">ニックネーム</label>
           <span class="indispensable">必須</span>
        </div>
         <%= f.text_field :nickname ,class:"items-text", id:"item-name", placeholder:"ニックネーム", maxlength:"40" %>
      </div>
     
      <div class="form">
        <div class='form-text-wrap'>
          <label class="form-text">プロフィール</label>
          <span class="form-any">任意</span>
        </div>
        <%= f.text_field :profile, class:"items-text", id:"profile", placeholder:"プロフィール"%>
      </div>

       <div class="form">
        <div class="form-text">
          <label class="form-text">性別</label>
          <span class="indispensable">必須</span>
          <%= f.collection_select(:sex_id, Sex.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        </div>
      </div>
        <div class="sell-btn-contents">
          <%= f.submit "変更する" ,class:"sell-btn" %>
          <%=link_to 'もどる', user_path, class:"back-btn" %>
        </div>
    </div>
    <%# /プロフィール詳細 %>
  <% end %>

</div>

<%= render "shared/footer" %>

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class="main">
   <div class="user__wrapper">
      <h2 class="page-heading">
       <%= "#{@user.nickname}さんの情報"%>
      </h2>
        <div class="user-img-content">
          <% if @user.image.present?%>
            <%= image_tag @user.image, class: "user-box-img", size: "150x150" %>
          <% else %>
             <%= image_tag "profile.png", class: "user-box-img", size: "150x150" %>
          <% end %> 
        </div>
        <table class="table">
          <tbody>
            <tr>
              <th class="table__col1">名前</th>
              <td class="table__col2"><%= @user.nickname %></td>
            </tr>
            <tr>
              <th class="table__col1">プロフィール</th>
              <td class="table__col2"><%= @user.profile %></td>
            </tr>
            <tr>
              <th class="table__col1">性別</th>
              <td class="table__col2"><%= @user.sex.name %></td>
            </tr>
          </tbody>
        </table>

        <div class="comments">
          <h2 class="page-heading">
            <%= "#{@user.nickname}さんのコメント一覧" %>
          </h2>
          <div class="user__card">
            <% @comments.each do |comment| %>
                <li class="comments-list">
                  <%= link_to comment.hot_spring.name ,hot_spring_path(comment.hot_spring.id) %><br>
                  <span class="comment"><%= comment.content %></span>
                </li>
            <% end %>
          </div>
        </div> 
        <% if @user.id == current_user.id %>
          <%= link_to "プロフィール編集", edit_user_path(@user.id), method: :get, class: "user-red-btn" %> 
          <p class="or-text">or</p>
          <%= link_to "アカウント削除", user_path(@user.id), method: :delete, class: "user-destroy" %>
        <% end %>
      
  </div>

</div>


<%= render "shared/footer" %>