config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'hot_springs#index'
  resources :hot_springs do
    resources :comments,only: [:index, :new, :create] 
    collection do
      get 'search'
    end
  end
   resources :users, only: [:show,:edit,:update,:destroy]

   post 'like/:id' => 'likes#create', as: 'create_like'
   delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

   post 'comments_like/:id' => 'comments_likes#create', as: 'create_comments_like'
   delete 'comments_like/:id' => 'comments_likes#destroy', as: 'destroy_comments_like'
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <h2 class='ad-footer-title'>
    今すぐ無料ダウンロード！
  </h2>
  <div class='store-btn'>
    <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
    <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
  </div>
</div>
<%# /下部広告部分 %>

<div class='footer'>
 
  <%= link_to image_tag("sauna-logo-white.png", class:"logo-white"), "#" %>
  <p>© TOTONOU</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
<div class='top-contents'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("sauna-logo.png", class:"sauna-icon"), "/" %>

        <%= search_form_for @q, url: search_hot_springs_path, class: "search-form" do |f| %>
          <%= f.search_field :name_or_city_or_block_or_building_cont , placeholder: "キーワードから探す", class: "input-box"%>
          <%= f.collection_select :prefecture_id_eq, Prefecture.all, :id, :name,include_blank: '都道府県から探す' ,class:"prefecture-box" %>

         <div class="search-button">
           <%= image_submit_tag("search.png", class: 'search-icon') %>
         </div>
        <% end %>
   
  </div>
  <div class='nav'>
    <ul class='lists-right'>
     <% if user_signed_in? %>
     <%#<li><%= link_to 'カテゴリー', "#", class: "category-list" </li>%>
      <li> <%= link_to '投稿する',new_hot_spring_path, class: "post" %></li>
     <%#li><%= link_to current_user.nickname, user_path(current_user.id), class: "user-nickname" %></li> 
      <li><%= link_to 'マイページ', user_path(current_user.id), class: "user-nickname" %></li> 
     <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li> 
     <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
     <% end %>
    </ul>
  </div>
  <div class='title-contents'>
    <h2 class='service-title'>
      TOTONOU
    </h2>
    <p class='service-explain'>
      全国のサウナの情報を共有できる
    </p>
    <p class='service-explain'>
      サウナ好きのためのサイトです
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
      <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
    </div>
  </div>
  
</header>

app/views/shared/_likes.html.erb
                  <% if hot_spring.liked_by?(current_user) %>
    <p>
      <!--remote: trueを追加-->
      <%= link_to post_likes_path(hot_spring), method: :delete, remote: true do %>
        <i class="fas fa-heart"></i><%= hot_spring.likes.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
<!--remote: trueを追加-->
      <%= link_to hot_spring_likes_path(hot_spring), method: :post, remote: true do %>
        <i class="far fa-heart"></i><%= hot_spring.likes.count %> いいね
      <% end %>
    </p>
  <% end %>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>TOTONOU利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%= image_tag "sauna-logo.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("sauna-logo.png", class:"second-logo"), "/" %>
</header>