config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'hot_springs#index'
  resources :hot_springs do
    resources :comments,only: [:index, :new, :create] 
    collection do
      get 'search'
    end
  end
   resources :users, only: [:show,:edit,:update,:destroy]

   post 'like/:id' => 'likes#create', as: 'create_like'
   delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

   post 'comments_like/:id' => 'comments_likes#create', as: 'create_comments_like'
   delete 'comments_like/:id' => 'comments_likes#destroy', as: 'destroy_comments_like'
end

app/models/hot_spring.rb
class HotSpring < ApplicationRecord
  belongs_to :user
  has_one :man_sauna, dependent: :destroy
  has_one :woman_sauna, dependent: :destroy
  has_one_attached :image, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture
  
end

app/controllers/hot_springs_controller.rb
class HotSpringsController < ApplicationController
  before_action :move_to_sign_up, only: [:create, :edit,:search]
  before_action :set_hot_spring, only: [:show, :edit, :update]
  before_action :set_q, only: [:index, :show, :search,:edit, :new]
  def index
    @hot_springs = HotSpring.all
    @saunas = Sauna.new
    @comments = Comment.all
  end

  def new
    @sauna = Sauna.new
  end

  def create
    @sauna = Sauna.new(sauna_params)
    if @sauna.valid?
      @sauna.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comments = @hot_spring.comments.includes(:user)
    @comment = Comment.new
    
  end

  def edit
    hot_spring_attributes = @hot_spring.attributes
    @sauna = Sauna.new(hot_spring_attributes)
  end

  def update

    @sauna = Sauna.new(sauna_params)
    @sauna.image ||= @hot_spring.image.blob if @hot_spring.image.present?
    if @sauna.valid? 
       @sauna.update(sauna_params, @hot_spring)
       redirect_to root_path
    else
      render :edit
    end
  end

  def search
    @results = @q.result
  end

  
  private

  def sauna_params
    params.require(:sauna).permit(:image,:name,:prefecture_id,:postcode ,:city,:block,:building,:homepage,:hot_temperture,:cold_temperture,:people_count,:remarks,:w_hot_temperture,:w_cold_temperture,:w_people_count,:w_remarks,:hot_spring_id).merge(user_id: current_user.id)
  end

  def set_hot_spring
    @hot_spring = HotSpring.find(params[:id])
  end

  def move_to_sign_up
    redirect_to new_user_session_path unless user_signed_in?
  end


  def set_q
    @q = HotSpring.ransack(params[:q])
  end
end

app/helpers/hot_springs_helper.rb
module HotSpringsHelper
end

app/views/hot_springs/edit.html.erb
<%# cssは商品出品のものを併用しています。
app/assets/stylesheets/items/new.css %>
<%= render "shared/second-header"%>
<div class="items-sell-contents">
  <div class="items-sell-main">
    <h2 class="items-sell-title">施設の情報を入力</h2>
    <%= form_with model:@sauna,url: hot_spring_path(@hot_spring.id), method: :patch,local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>
    
    <%# 商品画像 %>
    <div class="img-upload">
      
      <div class="weight-bold-text">
        施設外観画像
        <span class="indispensable">任意</span>
      </div>

      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>

    </div>
    <%# /商品画像 %>
    
    
      <div class="weight-bold-text">
        施設名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :name ,class:"items-text", id:"item-name", placeholder:"施設名（必須 40文字まで)", maxlength:"40" %>
  

    <%# 施設の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">施設の詳細
      </div>
     
      <div class="form">
        <div class='form-text-wrap'>
          <label class="form-text">郵便番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :postcode, class:"items-text", id:"city", placeholder:"例）123-4567"%>
      </div>

       <div class="form">
        <div class="form-text">
          都道府県
          <span class="indispensable">必須</span>
          <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name,  { include_blank: "---" }, {class:"select-box", id:"item-category"}) %>
        </div>
      </div>

      <div class="form">
        <div class='form-text-wrap'>
          <label class="form-text">市区町村</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :city, class:"items-text", id:"city", placeholder:"例）横浜市緑区"%>
      </div>

      <div class="form">
        <div class='form-text-wrap'>
          <label class="form-text">番地</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :block, class:"items-text", id:"addresses", placeholder:"例）青山1-1-1"%>
      </div>

      <div class="form">
        <div class='form-text-wrap'>
          <label class="form-text">建物名</label>
          <span class="form-any">任意</span>
        </div>
        <%= f.text_field :building, class:"input-default", id:"building", placeholder:"例）柳ビル103"%>
      </div>

      <div class="form">
        <div class='form-text-wrap'>
          <label class="form-text">
          HP</label>
          <span class="form-any">任意</span>
        </div>
        <%= f.text_area :homepage, class:"items-text", id:"item-name", placeholder:"https://~", maxlength:"40" %>
      </div>
    </div>
    <%# /施設の詳細 %>

    <%# サウナについて %>

     <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>サウナについて</span>
        <span>男湯</span>
      </div>
      <div class='form-text-wrap'>
       <label class="form-text">
        サウナ室温度</label>
        <span class="form-any">任意</span>
      </div>
      <%= f.text_area :hot_temperture, class:"items-text", id:"item-name", placeholder:"例）100", maxlength:"40" %>

      <div class='form-text-wrap'>
      <label class="form-text">
        水風呂温度</label>
        <span class="form-any">任意</span>
      </div>
      <%= f.text_area :cold_temperture, class:"items-text", id:"item-name", placeholder:"例）15", maxlength:"40" %>

      <div class='form-text-wrap'>
      <label class="form-text">
        収容人数</label>
        <span class="form-any">任意</span>
      </div>
      <%= f.text_area :people_count, class:"items-text", id:"item-name", placeholder:"例）10", maxlength:"40" %>

      <div class='form-text-wrap'>
      <label class="form-text">
        備考</label>
        <span class="form-any">任意</span>
      </div>
      <%= f.text_area :remarks, class:"items-text", id:"item-name", placeholder:"例）サウナマット無し", maxlength:"40" %>

     <%# 女湯%>
     <div class="weight-bold-text question-text">
        <span>女湯</span>
      </div>
      <div class='form-text-wrap'>
      <label class="form-text">
        サウナ室温度</label>
        <span class="form-any">任意</span>
      </div>
      <%= f.text_area :w_hot_temperture, class:"items-text", id:"item-name", placeholder:"例）100", maxlength:"40" %>

      <div class='form-text-wrap'>
      <label class="form-text">
        水風呂温度</label>
        <span class="form-any">任意</span>
      </div>
      <%= f.text_area :w_cold_temperture, class:"items-text", id:"item-name", placeholder:"例）15", maxlength:"40" %>

      <div class='form-text-wrap'>
      <label class="form-text">
        収容人数</label>
        <span class="form-any">任意</span>
      </div>
      <%= f.text_area :w_people_count, class:"items-text", id:"item-name", placeholder:"例）10", maxlength:"40" %>

      <div class='form-text-wrap'>
      <label class="form-text">
        備考</label>
        <span class="form-any">任意</span>
      </div>
      <%= f.text_area :w_remarks, class:"items-text", id:"item-name", placeholder:"例）サウナマット無し", maxlength:"40" %>
    </div>
    <%# /サウナについて%>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', hot_spring_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

</div>

<%= render "shared/second-footer"%>

app/views/hot_springs/index.html.erb
<%= render "shared/header" %>

<div class='main'>
  <div class='column'>
    <h1 class="column-title">
      ととのう とは？
    </h1>
    <p class='column-text'>
      医学的には血中に興奮状態の時に出るアドレナリンが残っているのに、自律神経はリラックス状態の副交感神経優位になっている状態
      <br>感覚が研ぎ澄まされ、頭の雑念が消え去り、多幸感に満ちている状態のことをいいます！
    </p>
  </div>
  <%# 施設一覧 %>
  <div class='item-contents'>
    <h2 class='title'>温泉施設一覧</h2>
    
    <ul class='item-lists'>
    <% if @hot_springs.present? %>
      <% @hot_springs.each do |hot_spring|%>
      <li class='list'>
        <%= link_to hot_spring_path(hot_spring.id) ,class:'none-list' do %>
        <div class='item-img-content'>
          <% if hot_spring.image.present?%>
            <%= image_tag hot_spring.image, class: "item-img" %>
          <% else %>
             <%= image_tag "sample.png", class: "item-img" %>
          <% end %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= hot_spring.name %>
          </h3>
          <div class='item-price'>
            <table class='man-sauna'>
                <tr><th class='man-title'>男湯</th></tr>
               <tr> <td class='sauna-room'>サウナ室</td>
                <td><%= hot_spring.man_sauna.hot_temperture %>度</td></tr>
                <tr><td class='water-room'>水風呂</td>
                <td><%= hot_spring.man_sauna.cold_temperture %>度</td></tr>
            </table>
              
            <table class='woman-sauna'>
                <tr><th class='woman-title'>女湯</th></tr>
               <tr> <td class='sauna-room'>サウナ室</td>
                <td><%= hot_spring.woman_sauna.w_hot_temperture %>度</td></tr>
                <tr><td class='water-room'>水風呂</td>
                <td><%= hot_spring.woman_sauna.w_cold_temperture %>度</td></tr>
            </table>
            <div class='heart-btn' id="hot_spring_<%= hot_spring.id %>">
                <%= render 'likes/like',hot_spring: hot_spring %>    
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>
    <% else%>
      <li class='list'>
        <%= link_to '#' do %>
        <%= image_tag 'sample.png', class: "item-img" %>
        <div class='item-info'>
          <h3 class='item-name'>
            温泉施設を登録してね
          </h3>
          <div class='item-price'>
           
            <div class='heart-btn'>
             
              <%#= image_tag "heart.png", class:"heart-icon" %>
              <%#span class='heart-count'>0</span%>
            </div>
          </div>
        </div>
        <% end %>
      </li>
    <% end %>
    </ul>
  </div>
  <%# /商品一覧 %>

  <%# コメント一覧%>
  <div class='comment-contents'>
    <h2 class='title'>コメント一覧</h2>
    <ul class='comment-lists'>
      <% if @comments.present? %>
        <% @comments.each do |comment|%>
          <li class='list'>
            <div class='comment-info'>
              <h3 class='comment-name'>
                <%= link_to comment.user.nickname, user_path(comment.user.id) , class:'none-list' %>
              </h3>
              <div class='hot_spring-name'>
                <%= link_to comment.hot_spring.name, hot_spring_path(comment.hot_spring.id),class:'none-list' %>
              </div>
              <div class='comment-content'>
                <%= comment.content%>
              </div>
             <div class='heart-btn' id="comment_<%= comment.id %>">
                <%= render 'comments_likes/comments_like',comment: comment %>    
            </div>
            </div>
          </li>
        <% end %>
      <% else%>
          
        <li class='list'>
          <%= image_tag 'sample.jpeg', class: "comment-img" %>
          <div class='comment-info'>
            <h3 class='comment-name'>
              コメントを投稿してね
            </h3>
            <div class='heart-btn' >
             
            </div>
          </div>
        
        </li>
        
      <% end %>
    </ul>
  </div>
  <%# コメント一覧%>
</div>

<%= render "shared/footer" %>

app/views/hot_springs/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('sauna-logo.png' , size: '185x50'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">温泉施設の情報を入力</h2>
    <%= form_with model: @sauna, url: hot_springs_path, method: :post, local: true do |f| %>


    <%= render 'shared/error_messages', model: f.object %>

    <%# 施設画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        施設外観画像
        
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# 施設画像 %>
    
    <div class="new-items">
      <div class="weight-bold-text">
        施設名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"施設名（必須 40文字まで)", maxlength:"40" %>
    </div>
  

    <%# 施設の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">施設の詳細
      </div>
     
      <div class="form">
        <div class='form-text-wrap'>
          <label class="form-text">郵便番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :postcode, class:"items-text", id:"city", placeholder:"例）123-4567"%>
      </div>

       <div class="form">
        <div class="form-text">
          都道府県
          <span class="indispensable">必須</span>
          <%= f.collection_select(:prefecture_id, Prefecture.all, :id,:name, { include_blank: "---" }, {class:"select-box", id:"item-category"}) %>
        </div>
      </div>

      <div class="form">
        <div class='form-text-wrap'>
          <label class="form-text">市区町村</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :city, class:"items-text", id:"city", placeholder:"例）横浜市緑区"%>
      </div>

      <div class="form">
        <div class='form-text-wrap'>
          <label class="form-text">番地</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :block, class:"items-text", id:"addresses", placeholder:"例）青山1-1-1"%>
      </div>

      <div class="form">
        <div class='form-text-wrap'>
          <label class="form-text">建物名</label>
          <span class="form-any">任意</span>
        </div>
        <%= f.text_field :building, class:"input-default", id:"building", placeholder:"例）柳ビル103"%>
      </div>

      <div class="form">
        <div class='form-text-wrap'>
          <label class="form-text">
          HP</label>
          <span class="form-any">任意</span>
        </div>
        <%= f.text_area :homepage, class:"items-text", id:"item-name", placeholder:"https://~", maxlength:"40" %>
      </div>
    </div>

<%# 施設の詳細%>

    <%# サウナについて %>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>サウナについて</span>
        <span>男湯</span>
      </div>
      <div class='form-text-wrap'>
       <label class="form-text">
        サウナ室温度</label>
        <span class="form-any">任意</span>
      </div>
      <%= f.text_area :hot_temperture, class:"items-text", id:"item-name", placeholder:"例）100", maxlength:"40" %>

      <div class='form-text-wrap'>
      <label class="form-text">
        水風呂温度</label>
        <span class="form-any">任意</span>
      </div>
      <%= f.text_area :cold_temperture, class:"items-text", id:"item-name", placeholder:"例）15", maxlength:"40" %>

      <div class='form-text-wrap'>
      <label class="form-text">
        収容人数</label>
        <span class="form-any">任意</span>
      </div>
      <%= f.text_area :people_count, class:"items-text", id:"item-name", placeholder:"例）10", maxlength:"40" %>

      <div class='form-text-wrap'>
      <label class="form-text">
        備考</label>
        <span class="form-any">任意</span>
      </div>
      <%= f.text_area :remarks, class:"items-text", id:"item-name", placeholder:"例）サウナマット無し", maxlength:"40" %>

     <%# 女湯%>
     <div class="weight-bold-text question-text">
        <span>女湯</span>
      </div>
      <div class='form-text-wrap'>
      <label class="form-text">
        サウナ室温度</label>
        <span class="form-any">任意</span>
      </div>
      <%= f.text_area :w_hot_temperture, class:"items-text", id:"item-name", placeholder:"例）100", maxlength:"40" %>

      <div class='form-text-wrap'>
      <label class="form-text">
        水風呂温度</label>
        <span class="form-any">任意</span>
      </div>
      <%= f.text_area :w_cold_temperture, class:"items-text", id:"item-name", placeholder:"例）15", maxlength:"40" %>

      <div class='form-text-wrap'>
      <label class="form-text">
        収容人数</label>
        <span class="form-any">任意</span>
      </div>
      <%= f.text_area :w_people_count, class:"items-text", id:"item-name", placeholder:"例）10", maxlength:"40" %>

      <div class='form-text-wrap'>
      <label class="form-text">
        備考</label>
        <span class="form-any">任意</span>
      </div>
      <%= f.text_area :w_remarks, class:"items-text", id:"item-name", placeholder:"例）サウナマット無し", maxlength:"40" %>
    </div>
    <%# サウナについて %>

   

   
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "登録する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">TOTONOU利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('sauna-logo.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎TOTONOU,Inc.
    </p>
  </footer>
</div>

app/views/hot_springs/search.html.erb
<%= render "shared/header" %>

  <div class='item-contents'>
    <h2 class='title'>検索結果</h2>
      <%if @results.present?%>

       <div class='sauna-lists'>

          <% @results.each do |hot_spring|%>
            <li class='sauna-list'>
               <%= link_to hot_spring_path(hot_spring.id) do %>

                  <div class='item-img-content'>
                     <% if hot_spring.image.present?%>
                        <%= image_tag hot_spring.image, class: "item-img" %>
                      <% else %>
                         <%= image_tag "sample.png", class: "item-img" %>
                      <% end %>
                  </div>

              <div class='item-info'>

                <h3 class='item-name'>
                  <%= hot_spring.name %>
                </h3>

                <div class='item-price'>

                  <table class='man-sauna'>
                    <tr><th class='man-title'>男湯</th></tr>
                    <tr> <td class='sauna-room'>サウナ室</td>
                    <td><%= hot_spring.man_sauna.hot_temperture %>度</td></tr>
                    <tr><td class='water-room'>水風呂</td>
                    <td><%= hot_spring.man_sauna.cold_temperture %>度</td></tr>
                  </table>
              
                  <table class='woman-sauna'>
                    <tr><th class='woman-title'>女湯</th></tr>
                    <tr> <td class='sauna-room'>サウナ室</td>
                    <td><%= hot_spring.woman_sauna.w_hot_temperture %>度</td></tr>
                    <tr><td class='water-room'>水風呂</td>
                    <td><%= hot_spring.woman_sauna.w_cold_temperture %>度</td></tr>
                  </table>

                  <div class='heart-btn' id="hot_spring_<%= hot_spring.id %>">
                    <%= render 'likes/like',hot_spring: hot_spring %>    
                  </div>

                </div>

              </div>
                <% end %>
            </li>
         <%end %>

        
       </div>

       <% else %>
        <h3>該当なし</h3>
       <% end %>
  </div>

<%= render "shared/footer" %>

app/views/hot_springs/show.html.erb
<%= render "shared/header" %>

<%# 施設の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @hot_spring.name %>
    </h2>
    <div class="item-img-content">
     <% if @hot_spring.image.present?%>
            <%= image_tag @hot_spring.image, class: "item-box-img" %>
          <% else %>
             <%= image_tag "sample.png", class: "item-box-img" %>
          <% end %>
    </div>
    

    

    <div class="item-explain-box">
      <span class="explain"><%= "施設情報" %></span>
    </div>
    <table class="detail-table">
    <tbody>
        <tr>
          <th class="detail-item">住所</th>
          <td class="detail-value">〒<%= @hot_spring.postcode%> <%= @hot_spring.prefecture.name %><%= @hot_spring.city%><%= @hot_spring.block%><%= @hot_spring.building%></td>
        </tr>
        <tr>
          <th class="detail-item">ホームページ</th>
          <td class="detail-value"><%= @hot_spring.homepage %></td>
        </tr>
    </tbody>
    </table>
    <table class="detail-table">
      <span>男湯</span>
      
        <tr>
          <th class="detail-item">サウナ室温度</th>
          <td class="detail-value"><%= @hot_spring&.man_sauna.hot_temperture %></td>
        </tr>
        <tr>
          <th class="detail-item">水風呂温度</th>
          <td class="detail-value"><%= @hot_spring&.man_sauna.cold_temperture %></td>
        </tr>
        <tr>
          <th class="detail-item">収容人数</th>
          <td class="detail-value"><%= @hot_spring&.man_sauna.people_count %></td>
        </tr>
        <tr>
          <th class="detail-item">備考</th>
          <td class="detail-value"><%= @hot_spring&.man_sauna.remarks %></td>
        </tr>
      </tbody>
     </table>

     <table class="detail-table">
       <span>女湯</span>
      <tbody>
       
        <tr>
          <th class="detail-item">サウナ室温度</th>
          <td class="detail-value"><%= @hot_spring&.woman_sauna.w_hot_temperture %></td>
        </tr>
        <tr>
          <th class="detail-item">水風呂温度</th>
          <td class="detail-value"><%= @hot_spring&.woman_sauna.w_cold_temperture %></td>
        </tr>
        <tr>
          <th class="detail-item">収容人数</th>
          <td class="detail-value"><%= @hot_spring&.woman_sauna.w_people_count %></td>
        </tr>
        <tr>
          <th class="detail-item">備考</th>
          <td class="detail-value"><%= @hot_spring&.woman_sauna.w_remarks %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <div class='heart-btn' id="hot_spring_<%= @hot_spring.id %>">  
           <%= render 'likes/like',hot_spring: @hot_spring %>
        </div>
      </div>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な投稿の通報</span>
      </div>
    </div>
  </div>
  <%# /商品の概要 %>


 <% if user_signed_in? %>
    <%= form_with model: [@hot_spring,@comment], id: "comment-form"  do |f|%>
     <div class="comment-box">
      <%= f.text_area :content ,class: "comment-text" %>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
    <%= f.submit "コメントをする", class: "comment-btn" %>
        <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
        
    
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :images, id:"item-image",name: 'comment[images][]', data: {index: 0} %>
      </div>
      <div id="previews"></div>
    <% end %>
  <% end %>

  <div id="comments">
    <h4>＜コメント一覧＞</h4>
      <% @hot_spring.comments.each do |comment| %>
        <div class="comment">
          <p class="user-info"><%= link_to comment.user.nickname, user_path(comment.user.id) %>： </p>
          <p><%= comment.content%></p>
          <% if comment.images.attached? %>
          <%= image_tag comment.images[0].variant(resize: '300x300'), class: "main-image" %><br>
             <div class="other-images">
                <% comment.images[1..-1].each do |image| %>
                <div class="other-image">
                <%= image_tag image.variant(resize: '300x300') %>
                </div>
               <%end%>
              </div>
          <% end %>
        </div>
      <% end %>
  </div>
    </div>
  

  

<% if user_signed_in? %>
    <%= link_to "施設情報の編集", edit_hot_spring_path(@hot_spring.id), method: :get, class: "item-red-btn" %>
<% end %>
   
</div>



<%= render "shared/footer" %>